moonch3/urls.py
from django.contrib import admin
from django.urls import path ,include ,re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve


urlpatterns = [
    path('' , include('moonweb.urls') ) ,


    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT,})
]  +   static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

moonweb/urls.py
from django.contrib import admin
from django.urls import path ,include ,re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from moonweb.eventpy.viewevents import ListEvent, deleteEvent, editEvent, likeEvent, makeEvent, viewEvent

from . import views
from .views import (
    UserAuthen
)

from moonweb.eventpy import *



urlpatterns = [
    path('dash/' , views.dashboard , name='dash') ,
    path('' , views.Home , name='Home'),
    path('hom/', views.sayhi, name='home'),
    path('kamra/<uuid:id>/callmeroom/', views.kamra,name='kamra'),
    path('create/', views.create ,name='create'),
    path('edit/<uuid:id>/',views.edit, name='edit'),
    path('uploadphoto/<str:id>/' , views.addnotePhoto , name='uploadnoteimg' ) , # add note image 
    path('notesetting/<str:id>/' , views.noteSetting , name='notesetting'),
    path('delete/<uuid:id>/', views.deleteNote,name='delete'),
    path('register/', views.register,name='register'),
    path('login/', views.loginMe,name='login'),
    path('logout/', views.logoutMe,name='logout'),
    path('profile/', views.profile ,name='userprofile'),
    path('deactivate' , views.deactivate , name='deactivate') ,
    path('myprofile/' , views.viewProfile , name='vpro' ) ,
    path('pro/<str:id>/' , UserAuthen.as_view() , name='prof') ,
    path('deactivateset' , views.deactivate , name='deactivatesetting') , # remove from setting 
    path('deactivate/' , views.deactivateUser , name='deactivate'),
    path('detail/<str:tle>/', views.detail , name='detail'),
    path('about/' , views.about , name='about') ,
    path('like/<uuid:pk>/' , views.Like , name="like") ,
    path('unlike/<uuid:pk>/' , views.unLike , name="unlike") ,
    path('blog/', views.addBlog , name="create-blog") ,
    path('blog/all/' , views.listBlog , name='allblog') ,
    path('blog/editblog/<uuid:id>', views.editBlog , name="edit-blog") ,
    path('blog/<uuid:pk>/', views.viewBlog , name="view-blog") ,
    path('blog/<uuid:pk>/', views.LikeBlog , name="like-blog") ,
    path('blog/editmessage/<str:id>/', views.editmessage , name='editmess' ) , 
    path('blog/delmess/<str:id>/' , views.deleteMessage , name='delmess') , 
    path('setting/user/okok/', views.Setting , name="setting") ,
    path('setting/user/okok/priv', views.Private , name="priv") ,
    path('setting/user/okok/viewpriv/<uuid:id>/', views.viewPrivate , name="viewpriv") ,
    #path('register/', CreateUser.as_view() , name='register'),
    #path('login/', LoginView.as_view() , name='login'),

    path('contact/' , views.contactus , name='contactus'),




    # event start from here

    path('event/createevent/' , makeEvent , name='createevent' ) ,
    path('event/homeevent/' , ListEvent , name='homeevent' ) ,
    path('event/<str:id>/viewevent/' , viewEvent , name='viewevent' ) ,
    path('event/<str:id>/deleteevent/' , deleteEvent , name='deleteevent' ) ,
    path('event/<str:id>/likeevent/' , likeEvent , name='likeevent' ) ,
    path('event/<str:id>/editevent/' , editEvent , name='editevent' ) ,
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT,})
]  +   static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

moonch3api/models.py
from pyexpat import model
from django.db import models
from django.contrib.auth.models import User
from django.forms import SlugField
from ckeditor.fields import RichTextField
# Create your models here.
import uuid
from datetime import datetime,timedelta
from django.contrib.auth.models import AbstractUser ,AbstractBaseUser ,BaseUserManager ,PermissionsMixin

from django.conf import settings


class UserManager( BaseUserManager ):
    def create_user(self, email , password = None ):
        if not email :
            raise ValueError('Email is Required!')
        user = self.model(
            email=self.normalize_email(email),
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self , email , password ) : # instance object inheritance just like abstract or interface in java
        if password is None :
            raise ValueError("Password Needed")
        user = self.create_user(email, password)
        user.is_superuser = True
        user.is_staff = True
        user.save()
        return user

# create user 
class User( AbstractBaseUser , PermissionsMixin ) :
    #id = models.UUIDField(primary_key=True , default=uuid.uuid4, editable=False)
    username = models.CharField(max_length=100)
    email = models.CharField(max_length=100, unique=True , verbose_name='Email Address', )
    image = models.ImageField( upload_to ="user/" , null=True  , blank=True, default='defaults.png' , max_length=100)
    phone_number = models.CharField(max_length=10, unique=True, null=True, blank=True)
    password = models.CharField(max_length=100)
    #username = None
    is_active = models.BooleanField(default=True)
    is_staff  =  models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    USERNAME_FIELD = 'email'
    REQUIED_FIELDS = ['username']
    objects = UserManager()


    def __str__(self):
        return self.email
    # UserApi._meta.get_field_by_name('email')[0]._unique=True

    class Meta:
        db_table = 'user'



      

class Note(models.Model):
    #host  = models.CharField(max_lengtg=100)
    id = models.UUIDField(primary_key = True, default = uuid.uuid4, editable = False)
    title = models.CharField(max_length= 30)
    body  = models.TextField()
    images = models.ImageField( upload_to ="imagenote/" , null=True  , blank=True, default='defaults.png' , max_length=100)
    date  = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    creator   = models.ForeignKey(User, on_delete=models.CASCADE)
    #editor = models.ForeignKey(User, on_delete=models.CASCADE)
    likes  = models.ManyToManyField( User, related_name='title')
    unlikes  = models.ManyToManyField( User, related_name='titles')
    image   = models.ImageField(upload_to="images/" , null=True  , default='defaults.png', max_length=100  )
    particpent = models.ManyToManyField(User, related_name='particpent',blank=True)
    private   = models.BooleanField(default=False)

    class META:
        ordering = ['-title']

    def total_likes(self):
        return self.likes.count()

    def total_unlikes(self):
        return self.unlikes.count()

    def getPart(self) :
        return self.particpent 

    def __str__(self):
        return self.title


class Message(models.Model):
    id = models.UUIDField(primary_key = True, default = uuid.uuid4, editable = False)
    note    = models.ForeignKey(Note ,on_delete=models.CASCADE) #models.SET_NULL 
    message = models.TextField()
    images = models.ImageField( upload_to ="messimage/" , null=True  , blank=True, default='defaults.png' , max_length=100)
    user    = models.ForeignKey(User, on_delete=models.CASCADE)
    #send_image = models.ImageField(null=True , blank=True, upload_to="images/")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)  
    class META:
        ordering = ['-title']


    def __str__(self):
        return self.message[0:50]


class Blog(models.Model):
    id = models.UUIDField(primary_key = True, default = uuid.uuid4, editable = False)
    user    = models.ForeignKey(User , on_delete=models.CASCADE)
    header  = models.SlugField() # CharField(max_length=50)
    blog =    RichTextField()
    #blog    = models.TextField()
    likes   = models.ManyToManyField( User , related_name='header')
    created = models.DateTimeField(auto_now_add=True) 

    def total_like(self):
        return self.likes.count()

    def totalblog(self):
        if self.user :
            return f"{self.header } :> {chr(128125)} "

    def __str__(self):
        #t = self.totalblog()
        #form = "{}:{}".format(self.user , t)
        return self.header

# class Themes( models.Model ) :
#     id = models.UUIDField(primary_key = True, default = uuid.uuid4, editable = False)
#     user  = models.ForeignKey(User , on_delete=models.CASCADE)
#     color = models.CharField(max_length= 50)
#     seted = models.DateTimeField(auto_now_add=True) 

# 
# class Event( models.Model ) :
#     id = models.UUIDField(primary_key = True, default = uuid.uuid4, editable = False)
#     user  = models.ForeignKey(User , on_delete=models.CASCADE)
#     image   = models.ImageField(null=True , blank=True, upload_to="images/")
#     title = models.CharField(max_length= 100)
#     body  = models.TextField()


class MindSet( models.Model ) :
    id = models.UUIDField(primary_key = True, default = uuid.uuid4, editable = False)
    user  = models.ForeignKey(User , on_delete=models.CASCADE)
    title = models.CharField(max_length= 100)
    body  = models.TextField()
    created = models.DateTimeField(auto_now_add=True)



class Ip( models.Model ) :
    id = models.UUIDField(primary_key = True, default = uuid.uuid4, editable = False)
    user = models.ForeignKey(User , on_delete=models.CASCADE)
    ip = models.GenericIPAddressField()
    created = models.DateTimeField(auto_now_add=True)


class Event(models.Model ) :
    id = models.UUIDField(primary_key = True, default = uuid.uuid4, editable = False)
    user = models.ForeignKey(User , on_delete=models.CASCADE)
    place = models.CharField(max_length=30) 
    desc = models.TextField()
    images = models.ImageField( upload_to ="eventimage/" , null=True  , blank=True, max_length=40)
    date = models.DateField()
    likes  = models.ManyToManyField( User, related_name='place')
    time = models.TimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True) 

    class Meta:
        ordering = ['-id']

    def __str__(self) -> str:
        return self.place

    def total_like(self) :
        return self.likes.count()
        

class UserDetail ( models.Model ) :
     # user info are store here after login 
    id = models.UUIDField(primary_key = True, default = uuid.uuid4, editable = False)
    user = models.ForeignKey(User , on_delete=models.CASCADE)
    ip = models.CharField(max_length=20) # REMOTE_ADDR
    user_agent = models.CharField(max_length=50) # HTTP_USER_AGENT
    method = models.CharField(max_length=10) # request.method
    path  = models.CharField(max_length=30) # request.path
    created = models.DateTimeField(auto_now_add=True) 

    def __str__(self) -> str:
        return self.user_agent

moonweb/models.py
from django.db import models

# Create your models here.

moonweb/forms.py
from django.forms import ModelForm
from django import forms
from moonch3api.models import Note,Message ,Blog ,User
from django.contrib.auth.forms import UserCreationForm

from django.contrib.auth import get_user_model
#from django.contrib.auth.models import User
User = get_user_model()

class UserImageForm(ModelForm) :
    class Meta:
        model = User
        fields = ['image']
class NoteForm(ModelForm):
    title = forms.CharField(label='title')
    title.widget.attrs['placeholder'] = "Title"

    class Meta:
        model = Note
        fields = '__all__' #['title','body','image'] # hide creator and likes
        exclude =['likes' , 'unlikes', 'creator' , 'particpent' , 'images']

class AddNoteForm( ModelForm ) :
    image = forms.ImageField(label=('image'),required=False, error_messages = {'invalid':("Image files only")}, widget=forms.FileInput)
    class Meta :
        model = Note 
        fields = ['image']
        
class ChatForm(ModelForm):
    class Meta:
        model = Message
        fields = ['message']

# class EditProfile(ModelForm):
#     class Meta:
#         model = User
#         fields = ['username','email']
        
class RegisterForm(UserCreationForm):
    #password = forms.CharField(widget=forms.PasswordInput)
    username = forms.CharField(label='Name') # label='text' place inside CF-method
    username.widget.attrs['placeholder'] = "☫ username ☫"
    email = forms.EmailField(label='Email') # label='text' place inside CF-method
    email.widget.attrs['placeholder'] = "☬ email ☬"
    password1 = forms.CharField(label='password',widget=forms.PasswordInput) # label='text' place inside CF-method
    password1.widget.attrs['placeholder'] = "☣ password ☣" # 9763
    password2 = None 
    #password2 = forms.CharField(label='',widget=forms.PasswordInput) # label='text' place inside CF-method
    #password2.widget.attrs['placeholder'] = "CONFIRM-PASSWORD"

    class Meta:
        model = User
        fields = ['username','email','password1'] # ,'password2'


class LoginUserForm(ModelForm):
    class Meta:
        #model = Register
        fields = ['username','password']

class BlogForm(ModelForm):
    class Meta:
        model = Blog
        fields = '__all__' #['title','body','image'] # hide creator and likes
        exclude =['user','likes']

moonweb/templates/moonweb/about.html
{% extends '../main/main.html' %}
{% block content %}
{% if user.is_authenticated %}
    <div class="wrapper2 set-center center_position">
        <div class="">
            <h4 class="card-title text-center">About </h4>
            <hr class="hrline">
            <h6 class="card-subtitle mb-2">{{ about.founder }}</h6>
            <p class="card-text"> {{ about.detail }} </p>

            <hr class="hrline">

            <div class="link d-flex ">
                <a href="#" class="card-link text-warning">{{ about.more }}</a>
                <a href="#" class="card-link text-warning">{{ about.top}}</a>
            </div>

        </div>
    </div>
{% else %}
<div id="about" class="wrapper2 set-center center_position ">
  <div><h2>About</h2></div>
  <p>
      Created in 2011, Hacker Typer arose from a simple desire to look like the
      stereotypical hacker in movies and pop culture. Since that time, it has brought
      smiles to millions of people across the globe. Plus, many of you have
      temporarily transformed into hackers yourselves, all from a few clicks on the
      keyboard (and some programming magic behind the scenes!).
  </p>
  <p>
      Also, if you are using Hacker Typer in any of your projects, videos or images,
      feel free to reach out! It s amazing to see what happens when people
      creativity interacts with this site.
  </p>
  <p>You can reach the developer here: <i>hackertyper@duiker101.net</i></p>
  <p>
      And please note: No, I will kindly not hack into anyone personal property, so
      please skip these requests. Thanks!
  </p>
  <p>
      You can find more info at
      <i><a target="_blank" href="https://duiker101.net">duiker101.net</a></i>
  </p>
  <div class="modal_footer">
      <a href="{% url 'Home' %}" class="btn btn-sm btn-outline-primary">Close</a>
  </div>
</div>

{% endif %} {% endblock content %}

moonweb/templates/moonweb/create.html
{% extends '../main/main.html' %}

{% block content %}



	{% if user.is_authenticated %}
	<div id="note1"> <!-- FIXED _-->
		<div class="wrapper2 center_box center-box">
			<div class="wrapper">
				<h5 class="text-center">Add Note</h5>
				<hr class="bor-b">
				<form method="POST" action="" enctype="multipart/form-data">
					{% csrf_token %}
					<div class="">
						<label for="" class="">{{ form.title.label }}</label>
						<p>
							{{ form.title }}
						</p>
					</div>

					<div class="">
						<label for="" class=""> {{ form.body.label }} </label>
						<p>

							{{ form.body }}
						</p>
					</div>

					<div class="inline-b">
						{{ form.private }}
						<label for="id_private" class=""> Set as Private </label>
						
					</div>
					<hr class="bor-b">
					<div class="ml-4">
						<button class="btn btn-sm btn-outline-primary" type='submit' name="act" value='Create'>Create</button>
					</div>
				</form>
			</div>	
		</div>
	</div>
	{% else %}
	<div class="center_position text-center">
        <div class="note">
            <div class="tem">
              <details><summary> Check this-out </summary>
                <ul class="items">
                  <div class="butt">    
                    Need you to Login
                  </div>                                      
                </ul>
              
              </details>
        </div> 

    </div>
	{% endif %}



{% endblock content %}

moonweb/templates/moonweb/deactivateuser.html
{% extends '../main/main.html' %}

{% block content %}
{% if user.is_authenticated %}
<div class="set-left-b wrapper2 center_room text-white">
	{% if messages %}
    {% for msg in messages %}
    	<div class="alert alert-info alert-dismissable">
        	<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{msg.message}}
        </div>
    {% endfor %}
    {% endif %}
	<form method="POST" action="">

		{% csrf_token %}
		<div class="btn-group">
			<a class="btn btn-sm btn-outline-primary" href="{% url 'vpro' %}">back</a>
			<button class="btn btn-sm btn-outline-primary" type="submit">Submit</button>
		</div>
		<hr class="hrline">
		<div class="m-4">
			<p>
				Type your name to delete your account permanently
			</p>
			<input type="text" name="username" id="username" placeholder="username">
		</div>
		
	</form>
</div>
{% else %}
<div class="center_position text-center">
	<div class="note">
		<div class="tem">
		  <details><summary> </summary>
			<ul class="items">
			  <div class="butt">    
				Need you to Login
			  </div>                                      
			</ul>
		  
		  </details>
	</div> 
</div>

{% endif %}
{% endblock content %}

moonweb/templates/moonweb/delete.html
{% extends '../main/main.html' %}
{% block content %}
{% if user.is_authenticated %}

<div class="text-white wrapper2 center_room mt-4">
	<form method="POST" action="{% url 'delete' del.id %}">

		{% csrf_token %}
		
		<div class="m-4">
			<p>Are you sure to delete : </p>
			<p>
				{{ del }}
			</p>
		</div>
		<div class="btn-group">
			<a class="btn btn-sm btn-outline-primary" href="{{ request.META.HTTP_REFERER }}">Cancel</a>
			<button class="btn btn-sm btn-outline-primary" type="submit">Delete</button>
		</div>
		
	</form>
</div>
{% else %}
<div class="center_position text-center">
	<div class="note">
		<div class="tem">
		  <details><summary> </summary>
			<ul class="items">
			  <div class="butt">    
				Need you to Login
			  </div>                                      
			</ul>
		  
		  </details>
	</div> 
</div>

{% endif %}
{% endblock content %}

moonweb/templates/moonweb/detail.html
{% extends '../main/main.html' %}
{% block content %}
	{% if user.is_authenticated %}
		<div class="center_room user_card text-white">
			
			<div class="btn-group float-right">{% if bio.private %}
				<a class="btn text-none btn-outline-primary btn-sm " href="{% url 'viewpriv' bio.id %}">⬅ </a>{% else %}	
				<a class="btn text-none btn-outline-primary btn-sm " href="{% url 'kamra' bio.id %}">⬅ </a>{% endif %}
				{% if request.user == bio.creator %}
				<a class="btn btn-info btn-sm float-right" href="{% url 'edit'   bio.id %}">Edit</a>
				<a class="btn btn-info btn-sm float-right" href="{% url 'uploadnoteimg'   bio.id %}">upload</a> 
				<a class="btn btn-info btn-sm float-right" href="{% url 'delete' bio.id %}">del</a>
				<a class="btn btn-info btn-sm float-right" href="{% url 'notesetting' bio.id %}">setting</a>
				{% endif %}
			</div>
			
			{% if bio.image %}
			<div class="image-container">
				<img class="noteimg" src="{{ bio.image.url }}"/>
				<div class="top-left">
					<h5>
						{{ uni }}.{{ bio | capfirst }}
					</h5> 
				</div>
				<div class="bottom-left">
					<small class="mb-4">
						<span>  {{ bio.date  | date:"Y/M/d h:m:s a"  }} </span>
					</small>
				</div>
				<div class="top-right"></div>
				<div class="bottom-right">
					<small> {{ bio.date  | timesince}} </small>
				</div>
			</div>
			{% endif %}
			<small>
				
				<a class="text-none" href="{% url 'prof' bio.creator.id %}"> 
					<img class="img-icon mb-2 ml-2" src="{{ bio.creator.image.url }}" alt="profile-image"> 
					<a class="text-white text-none ml-4" href="{% url 'prof' bio.creator.id %}"> Admin :  @{{ bio.creator }} </a>	
				</a>
				<hr class="bor-r"> 		
				
            </small>  
			<p>
				About : {{ bio.body }}
			</p>
			<div>
				<div class="tem">
					<details><summary> welcome </summary>
						<table class="items">
						{% for particpent in group %}
						{% if bio.creator  == particpent %}
						{% else %}
						<tr>
							<td class="py-2">
								<a class="text-none" href="{% url 'prof' particpent.id %}"> 
									<img class="img-icon" src="{{ particpent.image.url }}" alt="profile-image">  
								</a>
							</td>
							<td>
								<a class="text-white text-none" style="font-size: 13px;" href="{% url 'prof' particpent.id %}"> @{{ particpent }} </a>
							</td>
						</tr>
						{% endif %}
							{% empty %} {% endfor %}                                 
						</table>
				  </details>
			</div> 
		</div>
	{% else %}
		<div class="text-center bg-dark">
			You cannot view this page as a non-user
		</div>
		
	{% endif%}

{% endblock content %}

moonweb/templates/moonweb/error.html
{% extends '../main/main.html' %}


{% block content %}
    {% if user.is_authenticated %}

    <div class="container wrapper">
        <h1 class="text-center bg-primary">Error</h1>
        <p class="text-dark">
            Something is wrong with this Page
        </p>
    </div>
    {% else %}
    <div class="center_position text-center">
        <div class="note">
            <div class="tem">
              <details><summary> </summary>
                <ul class="items">
                  <div class="butt">    
                    Need you to Login
                  </div>                                      
                </ul>
              
              </details>
        </div> 
    </div>

    {% endif %}
{% endblock content %}

moonweb/templates/moonweb/home.html
{% extends '../main/main.html' %}
{% block content %}

    <div class="home" id="home">
        
        <div class="direction" id="direction">
            {% if messages %}
                {% for msg in messages %}
                    <div class="alert alert-info alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    {{msg.message}}
                    </div>
                {% endfor %}
            {% endif %}
            {{ request.META.HTTP_REFERER }}
            <div id="time" class="time"></div>
            <div id="clock"></div>
            <p class="text-white m-4">Make your mindset strong so that no one else disturbing you </p>
            <div id="move" >move</div>
        </div>
    </div>

    {% include '../main/footer.html' %}

{% endblock %}

moonweb/templates/moonweb/join.html
{% extends '../main/main.html' %}


{% block content %}


	{% if user.is_authenticated %}
		<h3>
			{{ user.username }}
			
		</h3>
		<p>Chat that you are join </p>
		{% for data in listem %}
		<h3>
			{{ forloop.counter }}.<a href="{% url 'kamra' data.id %}"> {{ data.title }}</a> 
		</h3>
		<hr/>
	{% endfor %}
		<hr/>

	{% else %}
	<div class="center_position text-center">
        <div class="note">
            <div class="tem">
              <details><summary> Check this-out </summary>
                <ul class="items">
                  <div class="butt">    
                    Need you to Login
                  </div>                                      
                </ul>
              
              </details>
        </div> 

    </div>
	{% endif %}

{% endblock content %}

moonweb/templates/moonweb/register.html
{% extends '../main/main.html' %}

{% block content %}

<div class="user_card center_room wrapper2">

	{% if messages %}
		{% for msg in messages %}
			<div class="alert alert-info alert-dismissable">
			<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
			{{msg}}
			
			</div>
		{% endfor %}
	{% endif %}



	<div class="w-full max-w-xs text-white ">
		<h5 class="text-center">
			REGISTER
		</h5>
		<hr class="hrline"/>
		<form class="shadow-md rounded px-8 pt-6 pb-8 mb-4 " method="POST" action="">
			{% csrf_token %}
		<div class="mb-2">
			<label class="ml-2" for="id_username" >
				{{ register.username.label }}
			</label>
		
			{{ register.username }} 
		
			
		</div>
		<div class="mb-2">
			<label class="ml-2" for="id_email">
				{{ register.email.label }} 
			</label>
			{{ register.email }} 
		</div>
		<div class="mb-2">
			<label class="ml-2" for="id_password">
				{{ register.password1.label }} 
			</label>
			{{ register.password1 }} 
		</div>
		<div class="mb-2">
			<input type="checkbox" class="ml-2" name="viewpass" id="password1view" onclick="showpass()">
			<label class=" text-sm font-bold ml-4 " for="password1view">
				show password
			</label>
			
		</div>
		<hr class="hrline">

		
		<div class="items-center text-center ">
			<button class="btn btn-sm btn-outline-primary" type='submit' value='Create'>create an account</button>
		</div>
		</form>
	</div>
  </div>

{% endblock content %}

moonweb/templates/moonweb/viewprofile.html
{% extends '../main/main.html' %}


{% block content %}

	{% if user.is_authenticated %}
	<div class="profile-card text-white">
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}
            <div>
                <h5 class="text-center mt-2">
                    {% if user.username|length > 25 %}
                    <marquee>  {{ user.username|slice:':50' }} </marquee>
                    {% else %}
                    {{ user.username }}
                    {% endif %}
                    
                </h5>
                <hr class="hrline">
                <div class="float-right mr-2">
                    {% if request.user != user.email %} {% else%}

                    <a href="{% url 'deactivate' %}" class="text-none float-right" title="delete user " style="font-size: 25px;">♺</a>  
                    {% endif %}

                    <div>

                        <label for="id_image">
                            <img class="photo" src="{{ user.image.url }}" >
                        </label>

                        {{form.image}}
                    
                    </div>
                </div>
                
                
                
            </div>

            <div style="margin: 24px 0; text-align: center;">
                

                <div style="text-align: center;">
                    <h1>{{ user.name  | title }} </h1>
                    <p class="title ">{{ user.email }}</p>

                    {% if request.user.email == user.email%}
                        {% if user.phone_number != None %}
                        <p>{{ user.phone_number | urlize }} </p>

                        {% else %}
                            <p> Set Phone Number </p>
                        {% endif %}
                    {% endif %}
                </div>
            </div>


            {% if request.user.email != user.email %}
            <a class="uppro text-none text-white" href="{% url 'userprofile' %} ">change-Profile</a>

            {% else %}
            <div class="btn-group uppro">
                <a class="btn btn-sm btn-outline-primary" href="{% url 'userprofile' %} ">change-Profile</a>
                <button class="btn btn-sm btn-outline-primary">upload</button>
                <a class="btn btn-sm btn-outline-primary" href="{% url 'deactivate' %} ">delete-account</a>
            </div>
            {% endif %}
        </form>
    </div>

   


	{% else %}
	<div class="center_position text-center">
        <div class="note">
            <div class="tem">
              <details><summary> Check this-out </summary>
                <ul class="items">
                  <div class="butt">    
                    Need you to Login
                  </div>                                      
                </ul>
              
              </details>
        </div> 

    </div>
	{% endif %}



 



{% endblock content %}